[common]
framework = arduino
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature@^3.9.0
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit AHTX0@^2.0.5
board_build.filesystem = littlefs

[env:esp32c6_lcd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-c6-devkitc-1
extends = common
platform_packages =
    platformio/tool-esptoolpy @ ~2.41100.0
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature@^3.9.0
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit AHTX0@^2.0.5
    lovyan03/LovyanGFX@^1.2.0
board_build.partitions = huge_app.csv
build_flags =
    -DLED_PIN=-1
    -DONE_WIRE_PIN=3
    -DI2C_SDA=4
    -DI2C_SCL=5
    -DUSE_DISPLAY

[env:esp32dev]
platform = espressif32
board = esp32dev
extends = common

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
extends = common
build_flags =
    -DLED_PIN=8
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DI2C_SDA=4
    -DI2C_SCL=3

[env:xiao_c3]
platform = espressif32
board = seeed_xiao_esp32c3
extends = common
build_flags =
    -DLED_PIN=11
    -DLED_ACTIVE_LOW
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DONE_WIRE_PIN=4
